export default[
{
login: "dazzlinbib",
id: 62376395,
node_id: "MDQ6VXNlcjYyMzc2Mzk1",
avatar_url: "https://avatars1.githubusercontent.com/u/62376395?v=4",
gravatar_id: "",
url: "https://api.github.com/users/dazzlinbib",
html_url: "https://github.com/dazzlinbib",
followers_url: "https://api.github.com/users/dazzlinbib/followers",
following_url: "https://api.github.com/users/dazzlinbib/following{/other_user}",
gists_url: "https://api.github.com/users/dazzlinbib/gists{/gist_id}",
starred_url: "https://api.github.com/users/dazzlinbib/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/dazzlinbib/subscriptions",
organizations_url: "https://api.github.com/users/dazzlinbib/orgs",
repos_url: "https://api.github.com/users/dazzlinbib/repos",
events_url: "https://api.github.com/users/dazzlinbib/events{/privacy}",
received_events_url: "https://api.github.com/users/dazzlinbib/received_events",
type: "User",
site_admin: false
},
{
login: "bcjcodes",
id: 61957905,
node_id: "MDQ6VXNlcjYxOTU3OTA1",
avatar_url: "https://avatars3.githubusercontent.com/u/61957905?v=4",
gravatar_id: "",
url: "https://api.github.com/users/bcjcodes",
html_url: "https://github.com/bcjcodes",
followers_url: "https://api.github.com/users/bcjcodes/followers",
following_url: "https://api.github.com/users/bcjcodes/following{/other_user}",
gists_url: "https://api.github.com/users/bcjcodes/gists{/gist_id}",
starred_url: "https://api.github.com/users/bcjcodes/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/bcjcodes/subscriptions",
organizations_url: "https://api.github.com/users/bcjcodes/orgs",
repos_url: "https://api.github.com/users/bcjcodes/repos",
events_url: "https://api.github.com/users/bcjcodes/events{/privacy}",
received_events_url: "https://api.github.com/users/bcjcodes/received_events",
type: "User",
site_admin: false
},
{
login: "emmanuelkolawole4",
id: 50505707,
node_id: "MDQ6VXNlcjUwNTA1NzA3",
avatar_url: "https://avatars2.githubusercontent.com/u/50505707?v=4",
gravatar_id: "",
url: "https://api.github.com/users/emmanuelkolawole4",
html_url: "https://github.com/emmanuelkolawole4",
followers_url: "https://api.github.com/users/emmanuelkolawole4/followers",
following_url: "https://api.github.com/users/emmanuelkolawole4/following{/other_user}",
gists_url: "https://api.github.com/users/emmanuelkolawole4/gists{/gist_id}",
starred_url: "https://api.github.com/users/emmanuelkolawole4/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/emmanuelkolawole4/subscriptions",
organizations_url: "https://api.github.com/users/emmanuelkolawole4/orgs",
repos_url: "https://api.github.com/users/emmanuelkolawole4/repos",
events_url: "https://api.github.com/users/emmanuelkolawole4/events{/privacy}",
received_events_url: "https://api.github.com/users/emmanuelkolawole4/received_events",
type: "User",
site_admin: false
},
{
login: "taiwoyewole",
id: 56822133,
node_id: "MDQ6VXNlcjU2ODIyMTMz",
avatar_url: "https://avatars2.githubusercontent.com/u/56822133?v=4",
gravatar_id: "",
url: "https://api.github.com/users/taiwoyewole",
html_url: "https://github.com/taiwoyewole",
followers_url: "https://api.github.com/users/taiwoyewole/followers",
following_url: "https://api.github.com/users/taiwoyewole/following{/other_user}",
gists_url: "https://api.github.com/users/taiwoyewole/gists{/gist_id}",
starred_url: "https://api.github.com/users/taiwoyewole/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/taiwoyewole/subscriptions",
organizations_url: "https://api.github.com/users/taiwoyewole/orgs",
repos_url: "https://api.github.com/users/taiwoyewole/repos",
events_url: "https://api.github.com/users/taiwoyewole/events{/privacy}",
received_events_url: "https://api.github.com/users/taiwoyewole/received_events",
type: "User",
site_admin: false
}
]