export default{
login: "codewarsfx",
id: 41517041,
node_id: "MDQ6VXNlcjQxNTE3MDQx",
avatar_url: "https://avatars3.githubusercontent.com/u/41517041?v=4",
gravatar_id: "",
url: "https://api.github.com/users/codewarsfx",
html_url: "https://github.com/codewarsfx",
followers_url: "https://api.github.com/users/codewarsfx/followers",
following_url: "https://api.github.com/users/codewarsfx/following{/other_user}",
gists_url: "https://api.github.com/users/codewarsfx/gists{/gist_id}",
starred_url: "https://api.github.com/users/codewarsfx/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/codewarsfx/subscriptions",
organizations_url: "https://api.github.com/users/codewarsfx/orgs",
repos_url: "https://api.github.com/users/codewarsfx/repos",
events_url: "https://api.github.com/users/codewarsfx/events{/privacy}",
received_events_url: "https://api.github.com/users/codewarsfx/received_events",
type: "User",
site_admin: false,
name: "innocent chidera shammah",
company: null,
blog: "http://codewarsfx.hashnode.dev/",
location: "lagos,Nigeria.",
email: null,
hireable: null,
bio: "Tech enthusiast trying to change the world one code at a time. sold out to learning. i love art too ...as a pass time i learn about art history.",
twitter_username: "codewarsfx",
public_repos: 29,
public_gists: 0,
followers: 4,
following: 13,
created_at: "2018-07-21T15:31:49Z",
updated_at: "2020-10-25T10:16:19Z"
}